# Generated by Django 5.0 on 2023-12-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('km', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pic1')),
            ],
        ),
    ]
