# Generated by Django 5.0 on 2023-12-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recar', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='ctry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recar.category'),
            preserve_default=False,
        ),
    ]
