# Generated by Django 5.0 on 2023-12-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recar', '0006_cars_ctry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='ctry',
            new_name='category',
        ),
    ]
